#pragma once

#include "natives.hpp"
#include <gta/joaat.hpp>


namespace big
{
	void applytattos() {
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_0"), -1, TRUE); 
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_1"), -1, TRUE); 
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_2"), -1, TRUE); 
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_3"), -1, TRUE); 
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_4"), -1, TRUE); 
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_5"), -1, TRUE); 
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_6"), -1, TRUE); 
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_7"), -1, TRUE); 
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_8"), -1, TRUE); 
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_9"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_10"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_11"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_12"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_13"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_14"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_15"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_16"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_17"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_18"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_19"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_20"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_21"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_22"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_23"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_24"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_25"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_26"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_27"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_28"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_29"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_30"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_31"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_32"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_33"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_34"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_35"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_36"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_37"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_38"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_39"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_40"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_41"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_42"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_43"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_44"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_45"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_46"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_47"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_48"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_49"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_50"), -1, TRUE);
            STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_51"), -1, TRUE);
	}

    void removetattos(){
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_0"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_1"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_2"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_3"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_4"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_5"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_6"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_7"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_8"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_9"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_10"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_11"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_12"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_13"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_14"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_15"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_16"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_17"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_18"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_19"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_20"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_21"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_22"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_23"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_24"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_25"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_26"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_27"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_28"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_29"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_30"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_31"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_32"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_33"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_34"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_35"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_36"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_37"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_38"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_39"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_40"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_41"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_42"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_43"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_44"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_45"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_46"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_47"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_48"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_49"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_50"), 0, TRUE);
        STATS::STAT_SET_INT(RAGE_JOAAT("TATTOO_FM_CURRENT_51"), 0, TRUE);
    }
}